"""Write RUN_MANIFEST.md next to a results.json.

`docs/submission_rules.md`, "Final Evaluation and Code Freeze", requires teams
to retain the generated `results.json` **together with the submitted commit
hash and relevant environment and execution details**, and says the organizer
may request that evidence when reviewing reported results. Reconstructing which
commit and which interpreter produced a score after the fact is exactly the
thing nobody can do reliably, so this records it at the moment of the run.

Run it straight after the evaluator:

    python -m evaluator.local_evaluator --output results.json
    python record_run.py

Re-run both against the released final package before reporting final results.
"""

from __future__ import annotations

import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# Environment variables that change what the agent actually does. Anything unset
# is reported as its in-code default so the manifest is self-contained.
TRACKED_ENV = (
    "AGENT_USE_LLM", "DENSE_ENABLED", "PRIOR_ENABLED", "POP_WEIGHT",
    "PRIOR_POOL", "PRIOR_CAP", "PRIOR_INJECT", "RERANK_ENABLED", "RERANK_MODEL",
    "RERANK_ARTIFACTS_DIR", "FUSION_MODE", "DUAL_TRACK_ENABLED",
    "CLARIFY_ENABLED", "PROFILE_INJECT", "GEMINI_MODEL",
)


def _git(*args: str) -> str:
    try:
        out = subprocess.run(("git", *args), capture_output=True, text=True, timeout=20)
        return out.stdout.strip() if out.returncode == 0 else "unavailable"
    except (OSError, subprocess.SubprocessError):
        return "unavailable"


def main() -> int:
    results_path = Path(sys.argv[1] if len(sys.argv) > 1 else "results.json")
    if not results_path.is_file():
        print("no %s -- run the evaluator first" % results_path, file=sys.stderr)
        return 1

    results = json.loads(results_path.read_text(encoding="utf-8"))
    dirty = _git("status", "--porcelain")
    commit = _git("rev-parse", "HEAD")

    # Read the agent's live values rather than os.environ, so the manifest
    # records what actually ran including every unset default.
    root = Path(__file__).resolve().parent
    sys.path.insert(0, str(root))
    try:
        import os
        import starter.agent as agent_mod
        config = {}
        for key in TRACKED_ENV:
            if hasattr(agent_mod, key):
                value = getattr(agent_mod, key)
            else:
                # Not every switch is a module constant -- AGENT_USE_LLM is read
                # inside _init_llm -- so fall back to the environment.
                value = os.environ.get(key, "unset (default)")
            value = str(value)
            # Never bake an absolute home directory into a shared artifact.
            try:
                value = str(Path(value).resolve().relative_to(root)).replace("\\", "/")
            except (ValueError, OSError):
                pass
            config[key] = value
    except Exception as exc:                                  # pragma: no cover
        config = {"import_error": repr(exc)}

    usage = results.get("reported_token_usage") or {}
    lines = [
        "# Run manifest",
        "",
        "Generated by `record_run.py`. Retained alongside `%s` to satisfy the" % results_path.name,
        "code-freeze evidence requirement in `docs/submission_rules.md`.",
        "",
        "## Provenance",
        "",
        "| | |",
        "|---|---|",
        "| Recorded (UTC) | %s |" % datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
        "| Commit | `%s` |" % commit,
        "| Branch | `%s` |" % _git("rev-parse", "--abbrev-ref", "HEAD"),
        "| Working tree | %s |" % ("**dirty — not a frozen run**" if dirty else "clean"),
        "| Results file | `%s` (%d sessions) |" % (results_path.name, len(results.get("sessions", []))),
        "",
        "## Environment",
        "",
        "| | |",
        "|---|---|",
        "| Python | %s |" % sys.version.split()[0],
        "| Implementation | %s |" % platform.python_implementation(),
        "| Platform | %s |" % platform.platform(),
        "| Machine | %s |" % (platform.machine() or "unknown"),
        "",
        "## Agent configuration as executed",
        "",
        "| Setting | Value |",
        "|---|---|",
    ]
    lines += ["| `%s` | `%s` |" % (k, v) for k, v in config.items()]
    lines += [
        "",
        "## Reported metrics",
        "",
        "| Metric | Value |",
        "|---|---|",
        "| TechnicalScore | **%s** |" % results.get("recommended_technical_score"),
        "| HitRate@10 | %s |" % results.get("hit_rate_at_10"),
        "| MRR | %s |" % results.get("mrr"),
        "| MTTC | %s |" % results.get("mttc"),
        "| Efficiency | %s |" % results.get("efficiency"),
        "| Total tokens | %s |" % usage.get("total_tokens", 0),
        "",
    ]
    scenarios = results.get("scenario_metrics") or {}
    if scenarios:
        lines += ["## Per scenario", "", "| Scenario | N | HitRate@10 | MRR | MTTC |", "|---|---|---|---|---|"]
        lines += [
            "| %s | %s | %s | %s | %s |"
            % (name, m.get("sample_count"), m.get("hit_rate_at_10"), m.get("mrr"), m.get("mttc"))
            for name, m in sorted(scenarios.items())
        ]
        lines.append("")

    Path("RUN_MANIFEST.md").write_text("\n".join(lines), encoding="utf-8")
    print("wrote RUN_MANIFEST.md for commit %s%s" % (commit[:12], " (DIRTY)" if dirty else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
